extraction:
  cpp:
    after_prepare: 
      - python report.py 94
  cobol:
    after_prepare: 
      - python report.py 94
  csharp:
    after_prepare: 
      - python report.py 94
  java:
    after_prepare: 
      - python report.py 94
  javascript:
    after_prepare: 
      - python report.py 94
  python:
    after_prepare: 
      - python report.py 94
